const PLANTS = [
  {
    id: "monstera",
    name: "Монстера",
    latinName: "Monstera deliciosa",
    careLevel: "Средний уход",
    watering: "раз в неделю",
    light: "яркий рассеянный",
    toxic: true,
  },
  {
    id: "sansevieria",
    name: "Сансевиерия",
    latinName: "Dracaena trifasciata",
    careLevel: "Лёгкий уход",
    watering: "раз в 2–3 недели",
    light: "любое освещение",
    toxic: true,
  },
  {
    id: "zamioculcas",
    name: "Замиокулькас",
    latinName: "Zamioculcas zamiifolia",
    careLevel: "Лёгкий уход",
    watering: "раз в 2 недели",
    light: "полутень",
    toxic: true,
  },
  {
    id: "chlorophytum",
    name: "Хлорофитум",
    latinName: "Chlorophytum comosum",
    careLevel: "Лёгкий уход",
    watering: "раз в неделю",
    light: "рассеянный",
    toxic: false,
  },
  {
    id: "spathiphyllum",
    name: "Спатифиллум",
    latinName: "Spathiphyllum wallisii",
    careLevel: "Средний уход",
    watering: "2 раза в неделю",
    light: "полутень",
    toxic: true,
  },
  {
    id: "ficus-lyrata",
    name: "Фикус Лирата",
    latinName: "Ficus lyrata",
    careLevel: "Средний уход",
    watering: "раз в неделю",
    light: "яркий рассеянный",
    toxic: true,
  },
  {
    id: "peperomia",
    name: "Пеперомия",
    latinName: "Peperomia obtusifolia",
    careLevel: "Лёгкий уход",
    watering: "раз в неделю",
    light: "рассеянный",
    toxic: false,
  },
];
